### ISSUE TITLE
RedHat 9 Fauxhai data missing

### ISSUE THREAD

**Issue by jjperry** [chef/fauxhai#20]
There is no RedHat EL 9 Fauxhai data, so RedHat 9 can't be tested with ChefSpec. 

# Describe the problem
RedHat EL 9 has been out since 2022-05-17 and yet it is still not supported in ChefSpec due to no Fauxhai data. 

## Software Version
RedHat 9

## Replication Case
Running `chef exec rspec` generates the message that the RedHat 9 is not a supported platform and to see PLATFORMS.md for supported platform. 

## Stacktrace
     Fauxhai::Exception::InvalidPlatform:
       Could not find platform 'redhat/9' on the local disk and an HTTP error was encountered when fetching from Github. A list of available platforms is available at https://github.com/chef/fauxhai/blob/main/PLATFORMS.md
     # ./spec/unit/recipes/custom_mount_spec.rb:12:in `new'
     # ./spec/unit/recipes/custom_mount_spec.rb:12:in `block (4 levels) in <top (required)>'
     # ./spec/unit/recipes/custom_mount_spec.rb:81:in `block (5 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # OpenURI::HTTPError:
     #   404 Not Found
     #   ./spec/unit/recipes/custom_mount_spec.rb:12:in `new'

## Possible Solution
Add RedHat 9 Fauxhai Data

**Comment by jjperry** [comment]
Code had been merged and verified as working when running 
```
chef exec rspec
``` 
and rspec code 
```
ChefSpec::SoloRunner.new(platform: redhat, version: 9)
```

**Comment by jjperry** [comment]
This is now resolved.
